/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ddevec_slowpath_fork_ForkProc */

#ifndef _Included_org_ddevec_slowpath_fork_ForkProc
#define _Included_org_ddevec_slowpath_fork_ForkProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ddevec_slowpath_fork_ForkProc
 * Method:    nativeDoFork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ddevec_slowpath_fork_ForkProc_nativeDoFork
  (JNIEnv *, jclass);

/*
 * Class:     org_ddevec_slowpath_fork_ForkProc
 * Method:    nativeKill
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ddevec_slowpath_fork_ForkProc_nativeKill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ddevec_slowpath_fork_ForkProc
 * Method:    createPipe
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ddevec_slowpath_fork_ForkProc_createPipe
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_ddevec_slowpath_fork_ForkProc
 * Method:    nativeGetPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ddevec_slowpath_fork_ForkProc_nativeGetPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
