/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ddevec_slowpath_fork_ForkProc_Status */

#ifndef _Included_org_ddevec_slowpath_fork_ForkProc_Status
#define _Included_org_ddevec_slowpath_fork_ForkProc_Status
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
